name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to your production branch
      - dev   # Add other branches as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name kinesis-lambda-processor-stack \
            --capabilities CAPABILITY_IAM
